name: NameBasedWhitelist
version: '${project.version}'
main: me.mrbonnie.namebasedwhitelist.NameBasedWhitelist
api-version: '1.20'
load: STARTUP

commands:
  wladd:
    description: add player to whitelist
  wlremove:
    description: remove player from whitelist
